services:
  web:
    image: ${IMAGE}
    container_name: myapp-web
    restart: unless-stopped
    ports:
      - "8080:8000"
version: "3.9"
services:
  app:
    image: ${IMAGE}
    env_file:
      - .env
    ports:
      - "8080:3000"
    restart: always
